name = "purple-mode-3382"
main = "service-worker-nuclear.js"
compatibility_date = "2026-01-19"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"

[site]
bucket = "./dist"
entry-point = "workers-site"
